### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by davidpestana** [CAMPUSCAMARAFP2021/Carrera_coches_lu#1]
Voy a revisar tu código y te explico que es lo que te falla.

> me sale un error que dice que vehiculo no esta definido a la hora de ponerlo en el html y no se por que

**Comment by davidpestana** [comment]
El primer error que tienes es....  

`  <script src="recorrido.js"></script>
`

Llamas al archivo como recorrido.js y ese archivo no existe... Por otro lado tienes otros dos archivos js a los que nunca llamas.

**Comment by luciaCalabrese** [comment]
vale, ya lo he corregido, gracias

**Comment by luciaCalabrese** [comment]
He puesto las herencias en vehiculo, solo, por que si las separo en diferentes clases no me las cuenta.

**Comment by davidpestana** [comment]
a que te refieres con que no te las cuenta?
